spring.application.name=SpringAI
spring.ai.openai.api-key=sk-test-1234567890abcdefghijklmnop
spring.ai.anthropic.api-key=sk-ant-test-abcdefghijklmnopqrstuvwxyz
spring.ai.ollama.chat.options.model=llama3.2:latest